---
title: "Survival analysis"
author: "Christelle Colin-Leitzinger"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
    theme: united
    highlight: pygments
    df_print: kable
    code_folding: hide
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      warning = FALSE,
                      message = FALSE,
                      cache = FALSE,
                      fig.align='center'
                      )
```

```{r library, echo = FALSE}
library(tidyverse)
library(gtsummary)
library(survminer)
library(survival)
theme_gtsummary_compact()
theme_set(theme_classic())
```

```{r load}
data <- 
  readxl::read_xlsx(paste0(here::here(), 
                           "/sample_status.xlsx"))
sequenced_patient_data <- read_csv(paste0(
  here::here(),
  "/processed data",
  "/De-identified breast data with sequenced sequential sample and clinical-CBC-Cytopenia-NADIR_2025-05-16.csv"))
```

```{r merge}
data_merge <- data %>% 
  mutate(deidentified_patient_id = paste0("breast_study_", sampleID)) %>% 
  left_join(., sequenced_patient_data %>% 
              distinct(deidentified_patient_id, .keep_all = TRUE),
            by = join_by(deidentified_patient_id))
```

```{r cleaning, echo = TRUE, class.source= 'fold-hide'}
data_merge <- data_merge %>% 
  mutate(tnm_stage = case_when(
    str_detect(tnm_stage, "0")       ~ "0",
    str_detect(tnm_stage, "1")       ~ "1",
    str_detect(tnm_stage, "2")       ~ "2",
    str_detect(tnm_stage, "3")       ~ "3",
    str_detect(tnm_stage, "4")       ~ "4",
    str_detect(tnm_stage, "99")      ~ NA_character_,
    TRUE                             ~ tnm_stage
  )) %>% 
  mutate(tnm_stage_cat = case_when(
    tnm_stage == "0" |
    tnm_stage == "1" |
    tnm_stage == "2"                 ~ "Early stage",
    tnm_stage == "3" |
    tnm_stage == "4"                 ~ "Late stage",
    TRUE                             ~ tnm_stage
  ), tnm_stage_cat = factor(tnm_stage_cat, levels = c("Early stage", "Late stage"))) %>% 
  mutate_at(c("er", "pr", "her2"), ~ factor(., levels = c("neg", "pos"))) %>% 
  mutate(status_CH = factor(status_CH, levels = c("noCH", "CH"))) %>% 
  mutate(cond = case_when(
    status_selection == "NegativeSelection"      ~ "Neg/Not impacted",
    status_selection == "NotChanged"             ~ "Neg/Not impacted",
    status_selection == "PositiveSelection"      ~ "Pos"
  ), cond = factor(cond, levels = c("Neg/Not impacted", "Pos"))) %>% 
  
  mutate(her2 = case_when(
    str_detect(deidentified_patient_id, "007422")      ~ "neg",
    TRUE                                               ~ her2
  ))
  
write_rds(data_merge %>% 
            select(deidentified_patient_id, 
                   age_at_sample, tnm_stage, tnm_stage_cat,
                   er, pr, her2, status_CH, status_selection, cond, 
                   os_event, os_time_from_tx_start_months, pfs_event, pfs_time_months), 
          "data_meerge_updated.rds")
```

# OS
# Overall population
## 1. Summary 
```{r Clinical table, echo = TRUE, class.source= 'fold-hide'}
data_merge %>% 
  select(age_at_sample, tnm_stage, tnm_stage_cat,
         er, pr, her2, status_CH, status_selection, cond) %>% 
  tbl_summary() %>% 
  bold_labels()
```

## 2. Hazard ratios and 95% confidence intervals
```{r, echo = TRUE, class.source= 'fold-hide'}
tbl1 <- tbl_uvregression(
  data_merge,
  method = coxph,
  y = Surv(time = os_time_from_tx_start_months, event = os_event),
  exponentiate = TRUE,
  include = c("age_at_sample", "tnm_stage_cat",
              "er", "pr", "her2", "status_CH"),
  # pvalue_fun = label_style_pvalue(digits = 2)
  ) %>%
  bold_p(t = .05) %>%
  add_nevent(location = "level") %>% add_n(location = "level") %>%
  bold_labels() %>% italicize_levels()

tbl2 <- coxph(Surv(time = data_merge$os_time_from_tx_start_months,
                   event = data_merge$os_event) ~ age_at_sample + tnm_stage_cat + er + pr + her2 + status_CH,
              data = data_merge)  %>%
  tbl_regression(exponentiate = TRUE) %>%
  bold_p(t = .05) %>%
  add_nevent(location = "level") %>% add_n(location = "level")

tbl_merge(list(tbl1, tbl2), 
          tab_spanner = c("**Univariable - each variable HR <br>is non adjusted**", 
                          "**Multivariable - each HR adjusted for <br>variables in table**"))
```

## 3. KM
The KM are not ajusted
```{r Survival, fig.height = 7, echo = TRUE, class.source= 'fold-hide'}
ggsurvplot(survfit(Surv(os_time_from_tx_start_months, os_event) ~ status_CH,
                   data=data_merge),
           title = "OS Analysis",
           font.main = c(20, "bold", "black"),
           font.x = c(18, "bold", "black"),
           font.y = c(18, "bold", "black"),
           font.legend = c(16, "black"),
           font.tickslab = c(16, "bold", "black"),
           size = 1.5,

           xlab = "Time (months)",
           legend = "top",
           legend.title = "",
           pval = TRUE,
           conf.int = FALSE,
           # Censor
           censor = TRUE
)
```

# Status selection subset
```{r, echo = TRUE, class.source= 'fold-hide'}
selection_subset <- data_merge %>% 
  filter(!is.na(cond))
```

## 1. Summary 
```{r Clinical table selection_subset, echo = TRUE, class.source= 'fold-hide'}
selection_subset %>% 
  select(age_at_sample, tnm_stage, tnm_stage_cat, 
         er, pr, her2, status_CH, status_selection, cond) %>% 
  tbl_summary() %>% 
  bold_labels()
```

## 2. Hazard ratios and 95% confidence intervals
```{r HR selection_subset, echo = TRUE, class.source= 'fold-hide'}
tbl1 <- tbl_uvregression(
  selection_subset,
  method = coxph,
  y = Surv(time = os_time_from_tx_start_months, event = os_event),
  exponentiate = TRUE,
  include = c("age_at_sample", "tnm_stage_cat",
              "er", "pr", "her2", "cond"),
  # pvalue_fun = label_style_pvalue(digits = 2)
  ) %>%
  bold_p(t = .05) %>%
  add_nevent(location = "level") %>% add_n(location = "level") %>%
  bold_labels() %>% italicize_levels()

tbl2 <- coxph(Surv(time = selection_subset$os_time_from_tx_start_months,
                   event = selection_subset$os_event) ~ age_at_sample + tnm_stage_cat + er + pr + her2 + cond,
              data = selection_subset)  %>%
  tbl_regression(exponentiate = TRUE) %>%
  bold_p(t = .05) %>%
  add_nevent(location = "level") %>% add_n(location = "level")

tbl_merge(list(tbl1, tbl2), 
          tab_spanner = c("**Univariable - each variable HR <br>is non adjusted**", 
                          "**Multivariable - each HR adjusted for <br>variables in table**"))
```

## 3. KM
```{r Survival selection_subset, fig.height = 7, echo = TRUE, class.source= 'fold-hide'}
ggsurvplot(survfit(Surv(os_time_from_tx_start_months, os_event) ~ cond,
                   data=selection_subset),
           title = "OS Analysis",
           font.main = c(20, "bold", "black"),
           font.x = c(18, "bold", "black"),
           font.y = c(18, "bold", "black"),
           font.legend = c(16, "black"),
           font.tickslab = c(16, "bold", "black"),
           size = 1.5,

           xlab = "Time (months)",
           legend = "top",
           legend.title = "",
           pval = TRUE,
           conf.int = FALSE,
           # Censor
           censor = TRUE
) %++% guides(colour = guide_legend(ncol = 1))
```

# PFS
# Overall population

## 1. Hazard ratios and 95% confidence intervals
```{r PFS, echo = TRUE, class.source= 'fold-hide'}
tbl1 <- tbl_uvregression(
  data_merge,
  method = coxph,
  y = Surv(time = pfs_time_months, event = pfs_event),
  exponentiate = TRUE,
  include = c("age_at_sample", "tnm_stage_cat",
              "er", "pr", "her2", "status_CH"),
  # pvalue_fun = label_style_pvalue(digits = 2)
  ) %>%
  bold_p(t = .05) %>%
  add_nevent(location = "level") %>% add_n(location = "level") %>%
  bold_labels() %>% italicize_levels()

tbl2 <- coxph(Surv(time = data_merge$pfs_time_months,
                   event = data_merge$pfs_event) ~ age_at_sample + tnm_stage_cat + er + pr + her2 + status_CH,
              data = data_merge)  %>%
  tbl_regression(exponentiate = TRUE) %>%
  bold_p(t = .05) %>%
  add_nevent(location = "level") %>% add_n(location = "level")

tbl_merge(list(tbl1, tbl2), 
          tab_spanner = c("**Univariable - each variable HR <br>is non adjusted**", 
                          "**Multivariable - each HR adjusted for <br>variables in table**"))
```

## 2. KM
The KM are not ajusted
```{r Survival PFS, fig.height = 7, echo = TRUE, class.source= 'fold-hide'}
ggsurvplot(survfit(Surv(pfs_time_months, pfs_event) ~ status_CH,
                   data=data_merge),
           title = "PFS Analysis",
           font.main = c(20, "bold", "black"),
           font.x = c(18, "bold", "black"),
           font.y = c(18, "bold", "black"),
           font.legend = c(16, "black"),
           font.tickslab = c(16, "bold", "black"),
           size = 1.5,

           xlab = "Time (months)",
           legend = "top",
           legend.title = "",
           pval = TRUE,
           conf.int = FALSE,
           # Censor
           censor = TRUE
)
```

# Status selection subset

## 1. Hazard ratios and 95% confidence intervals
```{r HR PFS selection_subset, echo = TRUE, class.source= 'fold-hide'}
tbl1 <- tbl_uvregression(
  selection_subset,
  method = coxph,
  y = Surv(time = pfs_time_months, event = pfs_event),
  exponentiate = TRUE,
  include = c("age_at_sample", "tnm_stage_cat",
              "er", "pr", "her2", "cond"),
  # pvalue_fun = label_style_pvalue(digits = 2)
  ) %>%
  bold_p(t = .05) %>%
  add_nevent(location = "level") %>% add_n(location = "level") %>%
  bold_labels() %>% italicize_levels()

tbl2 <- coxph(Surv(time = selection_subset$pfs_time_months,
                   event = selection_subset$pfs_event) ~ age_at_sample + tnm_stage_cat + er + pr + her2 + cond,
              data = selection_subset)  %>%
  tbl_regression(exponentiate = TRUE) %>%
  bold_p(t = .05) %>%
  add_nevent(location = "level") %>% add_n(location = "level")

tbl_merge(list(tbl1, tbl2), 
          tab_spanner = c("**Univariable - each variable HR <br>is non adjusted**", 
                          "**Multivariable - each HR adjusted for <br>variables in table**"))
```

## 2. KM
```{r PFS selection_subset, fig.height = 7, echo = TRUE, class.source= 'fold-hide'}
ggsurvplot(survfit(Surv(pfs_time_months, pfs_event) ~ cond,
                   data=selection_subset),
           title = "PFS Analysis",
           font.main = c(20, "bold", "black"),
           font.x = c(18, "bold", "black"),
           font.y = c(18, "bold", "black"),
           font.legend = c(16, "black"),
           font.tickslab = c(16, "bold", "black"),
           size = 1.5,

           xlab = "Time (months)",
           legend = "top",
           legend.title = "",
           pval = TRUE,
           conf.int = FALSE,
           # Censor
           censor = TRUE
) %++% guides(colour = guide_legend(ncol = 1))
```




